# Generated by Django 5.2.8 on 2025-11-22 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oda_no', models.CharField(max_length=10, verbose_name='Oda Numarası')),
                ('telefon_no', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('depozito_bakiyesi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depozito Bakiyesi')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('adres', models.TextField(verbose_name='Gidilecek Adres')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20)),
                ('yonetici_notu', models.TextField(blank=True, null=True, verbose_name='Red Nedeni / Yönetici Notu')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurt.ogrenci', verbose_name='Öğrenci')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem', models.CharField(max_length=20, verbose_name='Dönem (Örn: Ekim 2025)')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('son_odeme_tarihi', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('durum', models.CharField(choices=[('odenmedi', 'Ödenmedi'), ('odendi_online', 'Ödendi (Online)'), ('odendi_manuel', 'Ödendi (Elden/Havale)'), ('odendi_depozito', 'Ödendi (Depozitodan)')], default='odenmedi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yurt.ogrenci', verbose_name='Öğrenci')),
            ],
        ),
    ]
