# Generated by Django 5.2.8 on 2025-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yurt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fatura',
            name='odeme_aciklamasi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='odeme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='donem',
            field=models.CharField(max_length=20, verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='izintalebi',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Gidilecek Adres'),
        ),
        migrations.AlterField(
            model_name='izintalebi',
            name='yonetici_notu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='telefon_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
